services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT_EXPOSE}:${APP_PORT}"
    env_file:
      - .env
    networks:
      - ecommerce-network
    healthcheck:
      test: [
        "CMD",
        "python",
        "-c",
        "import requests; r = requests.get('http://localhost:${APP_PORT_EXPOSE}/api/health'); exit(0) if r.status_code == 200 else exit(1);"
      ]
      interval: 10s
      timeout: 10s
      retries: 3

networks:
  ecommerce-network:
    driver: bridge