services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "${DB_PORT_EXPOSE}:${DB_PORT}"
    env_file:
      - .env
    volumes:
      - user-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - ecommerce-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT_EXPOSE}:${APP_PORT}"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - ecommerce-network
    healthcheck:
      test: [
        "CMD",
        "python",
        "-c",
        "import requests; r = requests.get('http://localhost:${APP_PORT_EXPOSE}/api/health'); exit(0) if r.status_code == 200 else exit(1);"
      ]
      interval: 10s
      timeout: 10s
      retries: 3

volumes:
  user-db:
networks:
  ecommerce-network:
    driver: bridge