services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - user-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=userpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=User
    networks:
      - ecommerce-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - db
    networks:
      - ecommerce-network
    healthcheck:
      test: [
        "CMD",
        "python",
        "-c",
        "import requests; r = requests.get('http://localhost:8001/api/health'); exit(0) if r.status_code == 200 else exit(1);"
      ]
      interval: 10s
      timeout: 10s
      retries: 3

volumes:
  user-db:
networks:
  ecommerce-network:
    driver: bridge