FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

WORKDIR /app
COPY . /app

RUN ["chmod", "+x", "/app/entrypoint.sh"]
ENTRYPOINT ["./entrypoint.sh"]