"""0001

Revision ID: 550858adec44
Revises: 
Create Date: 2025-05-30 11:07:35.354642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '550858adec44'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('salt', sa.String(length=29), nullable=False),
    sa.Column('user_type', sa.Enum('CUSTOMER', 'CRM', 'ADMIN', 'REPORTER', 'VENDOR', name='useraccounttype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'INACTIVE', name='useraccountstatus'), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
